language: go

go: "1.10"

sudo: required

services: docker

install: make install

script: make test

before_deploy:
    - make build dockerize
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push richardleterrier/the-collector:latest

deploy:
    provider: releases
    api_key:
        secure: cBS86KcZkazpFB42q+lt6ipnAKCkWtZRuRdS7nEOaCCmsxk/OZBSdnOgYu4B6NfWukn7dwjd2YAejqmuwKa5iwJKjsTxXIw1KvfoWpFTJNFmFUMyqDITr5YC6yuOEywM0OrluisREEjiW+OzLdhRXLQDO/fyPNafjdpP1ep6aKA8FtXqHuYCoYGjVTDsLUZWcrr97ZpPAzJBmiGdQ7wKYcsQRsbKQXv0gnUo6zyCiIaiFyOynK1iBqAEMCTkB8++XOtR9P7YL1RJ87L7uLtimkRvU14IU8MetKlGSdo9OjTIC9XlSglNY02zAyRL7kwpDM6T3kkUYOhs9REnfJcIGbsm47DVE++oqiRcz3t3DQSv7fZh7GYRpwvUU8m35x1DnxnbP1xRbEvzUkC7luGSI1qqyvw96RWM1SUcBlA4aBdNIxFEsC390VtLm0606kB2J15JlSnRuUes81IVmtwtQrvFIurZVWfORD1D4orJZsrWrv4de0AjT80+4Z7PsLSDvGZipgPyDwO9mvkjX3P2Wwhf+a/zGdhhsvHfAe/ATvI5PJH2be+4/IWyPf/2LWLEV9SF9li1kKmu06n+1NSi5rNgOBukEUHi/X3esYxeGFe2y3j9oreDTt3TibUp//R7Rzjj5+0PXPayGoh9TIRQRKfWd3CfoT+X+V3w2WDSRBU=
    file: the-collector.zip
    skip_cleanup: true
    on:
        tags: true
        repo: richardlt/the-collector
